### ISSUE TITLE
Add negative examples

### ISSUE THREAD

**Issue by fwhite73** [qizhyuan/PRASEMap#5]
Hi, thank you for your work!

I was searching for a way to provide user feedback like it is done in the web application. (or hardcoded)

I can't find a method to add no match feedback.

The feedback given in the web application should go to which module?

Thank you

**Comment by qizhyuan** [comment]
Hi,

Thanks for your attention to our work! 

I think you can check the update_ent_eqv(self, ent_id, ent_cp_id, prob, force) method in the PARIS.py file, which could fix the probability of a given entity pair when force is set to True. In your case, you could set the prob to zero and force to True to add negative examples. The current implementation to utilize the negative feedback is simple and naive.  Specifically, our PARIS implementation will use the provided probability value of a given entity pair in the matching stage and this value will not be updated (if force is True) in each iteration of PARIS.  

Hope your research goes well!

**Comment by fwhite73** [comment]
I was able to add also negative examples and it worked very well!
But as I can see in the code, whenever I change graphs, the model gets reinitialised... if only data changes and I would like to use the model to predict new mappings between two graphs (with the same structures as the starting ones but different data inside), can I use the same model implementing the methods for the new graphs loading or is it necessary to retrain all the model?

**Comment by qizhyuan** [comment]
If I understand correctly, the "data" you mentioned refers to the name of an entity/attribute value. Unfortunately, the current version does not support the functionality of editing the graph nodes (but may support adding new nodes). The KG object is implemented as a static one and the functions we provided are mostly for "get" (see KG.py and prase_core.cpp).

One thing I want to mention is that the PARIS algorithm will match the literals (attribute values) of two graphs at first and use them as the initial seeds to perform further iterations. It could be fine if we only change the names of entities. But if the data of attribute values are changed, the mapping result could be changed due to different initial literal matching results.

If you do want to implement your functionality. Here are two possible choices I could figure out at this time:
1. Revise and add functions to the KG.py and prase_core.cpp files to support your feature;
2. Or, you can find the data mappings across the new and the old graphs, and then construct new graphs with the mappings discovered for old graphs inserted (use the update_ent_eqv function).

The first one requires more workload, and the second one is easier to do but with less efficiency.
